### PR TITLE
Embedposting Iframe: Level 1 iframe works in Firefox

### PR DESCRIPTION
**Pull request by hitesh96db**
This page can be reused for testing the posting process as well. But the level 1 iframe won't display in Firefox, so I've made the necessary changes which works for both Chrome and Firefox. Level 2 still doesn't work for Firefox, I couldn't find a way to get it to work. 
I've also added id's to make it easier to find the nodes while testing.

### CODE REVIEW

**Comment by smcgregor** [comment]
@SummerWish This is a test case you use/created. OK to merge?

**Comment by SummerWish** [comment]
yup.

**Comment by SummerWish** [comment]
I just add some commits to this PR, which contains my test page for seamless-posting.

**Comment by smcgregor** [comment]
This will be deployed to test.privly.org within 15 minutes.

**Pull request merged**
